version: '3.8'

services:
  # --- Node 1 ---
  node1:
    image: kv-store:latest
    container_name: kv-node-1
    hostname: kv-node-1
    ports:
      - "9091:9090"
    environment:
      - PEERS=kv-node-2:9090,kv-node-3:9090
      - HOSTNAME=node1
    volumes:
      - ./cluster-data/node1:/app/kv-data
    networks:
      - kv-net
    depends_on:
      - node2
      - node3

  # --- Node 2 ---
  node2:
    image: kv-store:latest
    container_name: kv-node-2
    hostname: kv-node-2
    ports:
      - "9092:9090"
    environment:
      - PEERS=kv-node-1:9090,kv-node-3:9090  # <--- ADDED THIS
      - HOSTNAME=node2
    volumes:
      - ./cluster-data/node2:/app/kv-data
    networks:
      - kv-net

  # --- Node 3 ---
  node3:
    image: kv-store:latest
    container_name: kv-node-3
    hostname: kv-node-3
    ports:
      - "9093:9090"
    environment:
      - PEERS=kv-node-1:9090,kv-node-2:9090  # <--- ADDED THIS
      - HOSTNAME=node3
    volumes:
      - ./cluster-data/node3:/app/kv-data
    networks:
      - kv-net

networks:
  kv-net:
    driver: bridge